/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { LotteryContract } from "./Lottery";
import { MathContract } from "./Math";
import { ParticipantContract } from "./Participant";
import { StringsContract } from "./Strings";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Lottery"): LotteryContract;
      require(name: "Math"): MathContract;
      require(name: "Participant"): ParticipantContract;
      require(name: "Strings"): StringsContract;
    }
  }
}

export { LotteryContract, LotteryInstance } from "./Lottery";
export { MathContract, MathInstance } from "./Math";
export { ParticipantContract, ParticipantInstance } from "./Participant";
export { StringsContract, StringsInstance } from "./Strings";
