/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ParticipantContract
  extends Truffle.Contract<ParticipantInstance> {
  "new"(
    nickname_: string,
    sender: string,
    meta?: Truffle.TransactionDetails
  ): Promise<ParticipantInstance>;
}

type AllEvents = never;

export interface ParticipantInstance extends Truffle.ContractInstance {
  nickname(txDetails?: Truffle.TransactionDetails): Promise<string>;

  wallet(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    nickname(txDetails?: Truffle.TransactionDetails): Promise<string>;

    wallet(txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
